#!/usr/bin/env python
# coding: utf-8

# In[95]:


import turtle
pen = turtle.Turtle()

# Input
mau_mai_nha = input("Nhập màu mái nhà (red/green/blue/yellow/etc.): ")
mau_tuong_nha = input("Nhập màu tường nhà (red/green/blue/yellow/etc.): ")
mau_cua_so = input("Nhập màu cửa sổ (red/green/blue/yellow/etc.): ")

# Thân nhà chính
turtle.goto(-200, 0)
turtle.fillcolor(mau_tuong_nha)
turtle.begin_fill()
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.end_fill()
# Mái nhà chính
turtle.fillcolor(mau_mai_nha)
turtle.begin_fill()
turtle.goto(-100, 60)
turtle.home()
turtle.goto(-200, 0)
turtle.end_fill()
# Cửa chính
turtle.penup()
turtle.goto(-120, -200)
turtle.pendown()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.forward(40)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(60)
turtle.end_fill()
# Cửa sổ 1
turtle.penup()
turtle.goto(-180, -40)
turtle.pendown()
turtle.fillcolor(mau_cua_so)
turtle.begin_fill()
turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.end_fill()
# Cửa sổ 2
turtle.penup()
turtle.goto(-20, -40)
turtle.pendown()
turtle.fillcolor(mau_cua_so)
turtle.begin_fill()
turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(40)
turtle.end_fill()
# Mái nhà phụ
turtle.penup()
turtle.goto(-100, 60)
turtle.pendown()
turtle.fillcolor(mau_mai_nha)
turtle.begin_fill()
turtle.goto(-20, 80)
turtle.goto(80, 20)
turtle.home()
turtle.end_fill()
# Thân nhà phụ
turtle.fillcolor(mau_tuong_nha)
turtle.begin_fill()
turtle.goto(80, 20)
turtle.goto(80, -180)
turtle.goto(0, -200)
turtle.home()
turtle.end_fill()
# Thân cây
turtle.penup()
turtle.goto(200, -200)
turtle.pendown()
turtle.fillcolor("brown")
turtle.begin_fill()
turtle.forward(40)
turtle.left(90)
turtle.forward(140)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(140)
turtle.end_fill()
# Thân cây 1
turtle.penup()
turtle.goto(160, -60)
turtle.pendown()
turtle.fillcolor("green")
turtle.begin_fill()
turtle.goto(220, -30)
turtle.goto(280, -60)
turtle.goto(160, -60)
turtle.end_fill()
# Thân cây 2
turtle.penup()
turtle.goto(160, -30)
turtle.pendown()
turtle.fillcolor("green")
turtle.begin_fill()
turtle.goto(220, 0)
turtle.goto(280, -30)
turtle.goto(160, -30)
turtle.end_fill()
# Thân cây 3
turtle.penup()
turtle.goto(160, 0)
turtle.pendown()
turtle.fillcolor("green")
turtle.begin_fill()
turtle.goto(220, 30)
turtle.goto(280, 0)
turtle.goto(160, 0)
turtle.end_fill()
# Thân cây 4
turtle.penup()
turtle.goto(160, 30)
turtle.pendown()
turtle.fillcolor("green")
turtle.begin_fill()
turtle.goto(220, 60)
turtle.goto(280, 30)
turtle.goto(160, 30)
turtle.end_fill()
# Thân cây 5
turtle.penup()
turtle.goto(160, 60)
turtle.pendown()
turtle.fillcolor("green")
turtle.begin_fill()
turtle.goto(220, 90)
turtle.goto(280, 60)
turtle.goto(160, 60)
turtle.end_fill()

# Tia mặt trời
turtle.penup()
turtle.goto(50, 380)
turtle.pendown()
turtle.forward(160)
turtle.penup()
turtle.goto(-30, 300)
turtle.left(90)
turtle.pendown()
turtle.forward(160)
turtle.penup()
turtle.goto(0, 350)
turtle.pendown()
turtle.goto(100, 250)
turtle.penup()
turtle.goto(0, 250)
turtle.pendown()
turtle.goto(100, 350)
# Mặt trời
turtle.penup()
turtle.goto(0, 300)
turtle.right(90)
turtle.pendown()
turtle.fillcolor("orange")
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()


turtle.bgcolor("#62D3FF");
turtle.done()

